language: go

go:
  - 1.8

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - ./lint_gofmt.sh
  - ./lint_metalinter.sh
  - go build .
  - cd cmd/emailbot-example && go build . && ./emailbot-example 2>&1 | grep Usage
